- hosts: webserver
  become: true
  tasks:
  - name: Install maven on servers
    command: sudo apt-get install maven -y
  - name: install docker on servers
    command: sudo apt-get install -y docker-ce
  - name: start docker on servers
    service: name=docker state=started
